## Preprocess data, write TAF data tables

## Before:
## After:

library(icesTAF)
#install.packages("pak") # if needed
#pak::pkg_install("r4ss/r4ss")
#pak::pkg_install("r4ss/r4ss@1.46.1") # install r4ss version 1.46.1
library(r4ss)
library(reshape2)
library(readxl)
library(openxlsx)
library(dplyr)
library(kableExtra)


mkdir("data")

path_origin<-getwd()
# DATA for model ----
path.data<-"boot/data" 
list.files(path.data)
# format data SS3 ----
mod_path <- "data" # model
data_path <- file.path(path.data, "anch2024.xlsx")
sheets<-excel_sheets(data_path)

parse_levels <- function (lvls, var_name) {
  m <- suppressWarnings(as.numeric(lvls))
  if (!anyNA(m)) return(data.frame(
    names = lvls,
    lower_incl = TRUE,
    lower_bound = m,
    upper_bound = c(tail(m, -1), Inf),  # NB: No data about final bound, assume open-ended
    upper_incl = FALSE,
    open_ended_upper = TRUE,
    stringsAsFactors = FALSE))
  
  m <- regmatches(lvls, regexec("^(\\[|\\()(.*),(.*)(\\]|\\))", lvls))
  if (all(vapply(m, length, numeric(1)) == 5)) return(data.frame(
    names = lvls,
    lower_incl = vapply(m, function (mm) identical(mm[[2]], '['), logical(1)),
    lower_bound = vapply(m, function (mm) as.numeric(mm[[3]]), numeric(1)),
    upper_bound = vapply(m, function (mm) as.numeric(mm[[4]]), numeric(1)),
    upper_incl = vapply(m, function (mm) identical(mm[[5]], ']'), logical(1)),
    open_ended_upper = is.infinite(as.numeric(tail(m, 1)[[1]][[4]])),
    stringsAsFactors = FALSE))
  
  stop("Unknown form of ", var_name, " levels, see ?cut for formatting: ", paste(lvls, collapse = ", "))
}

# Create new SS3 model ----
r4ss::copy_SS_inputs(
  dir.old = path.data,#system.file(file.path("extdata", "simple_small"), package = "r4ss"),
  dir.new = mod_path,
  overwrite = TRUE)

inputs <- r4ss::SS_read(dir = mod_path)


inputs$dat$Comments <- sprintf("#C %s model generated by ModelWizard", mod_path)

# Clear tables ####################
## data file ----
inputs$dat$fleetinfo <- inputs$dat$fleetinfo[c(),,drop = FALSE]
inputs$dat$catch     <- inputs$dat$catch[c(),,drop = FALSE]
inputs$dat$CPUEinfo  <- inputs$dat$CPUEinfo[c(),,drop = FALSE]
inputs$dat$CPUE      <- inputs$dat$CPUE[c(),,drop = FALSE]
inputs$dat$len_info  <- inputs$dat$len_info[c(),,drop = FALSE]
inputs$dat$lencomp   <- inputs$dat$lencomp[c(),,drop = FALSE]
inputs$dat$age_info  <- inputs$dat$age_info[c(),,drop = FALSE]
inputs$dat$agecomp   <- inputs$dat$agecomp[c(),,drop = FALSE]
inputs$dat$MeanSize_at_Age_obs <- inputs$dat$MeanSize_at_Age_obs[c(),,drop = FALSE]
## control file ----
inputs$ctl$MG_parms         <- inputs$ctl$MG_parms[c(),,drop = FALSE]
inputs$ctl$SR_parms         <- inputs$ctl$SR_parms[c(),,drop = FALSE]
inputs$ctl$Q_options        <- inputs$ctl$Q_options[c(),,drop = FALSE]
inputs$ctl$Q_parms          <- inputs$ctl$Q_parms[c(),,drop = FALSE]
#inputs$ctl$size_selex_types <- inputs$ctl$size_selex_types[c(),,drop = FALSE]
#inputs$ctl$size_selex_parms <- inputs$ctl$size_selex_parms[c(),,drop = FALSE]
inputs$ctl$age_selex_types  <- inputs$ctl$age_selex_types[c(),,drop = FALSE]
inputs$ctl$age_selex_parms  <- inputs$ctl$age_selex_parms[c(),,drop = FALSE]
inputs$ctl$lambdas          <- inputs$ctl$lambdas[c(),,drop = FALSE]

# DATA FILE ----
### Create area and fleet definitions ----
inputs$dat$N_areas    <-1#length(readxl::read_excel(data_path, "area", na = c("", "NA"))$name) #1L #'*sacar de "anch.xlsx" - area* 
inputs$dat$Nfleets    <-length(readxl::read_excel(data_path, "fleet", na = c("", "NA"))$name)
inputs$dat$fleetnames <-readxl::read_excel(data_path, "fleet", na = c("", "NA"))$name
### Create time definitions ----
inputs$dat$styr  <- readxl::read_excel(data_path, "time", na = c("", "NA"))$year_min #1979L #'*sacar de "anch.xlsx" = time*
inputs$dat$endyr <- readxl::read_excel(data_path, "time", na = c("", "NA"))$year_max #2023L #'*sacar de "anch.xlsx" = time*
inputs$dat$nseas <- as.numeric(readxl::read_excel(data_path, "time", na = c("", "NA"))$steps) #4L    #'*sacar de "anch.xlsx" = time*
inputs$dat$months_per_seas <- rep(12/inputs$dat$nseas,inputs$dat$nseas) #3L
### Create stock definition ---- 
inputs$dat$spawn_month  <-1
inputs$dat$Nsexes       <-1
inputs$dat$Ngenders     <-inputs$dat$Nsexes
inputs$dat$Nages        <-readxl::read_excel(data_path, "stock", na = c("", "NA"))$age_max 
inputs$dat$lbin_method  <-2 # option SS3
inputs$dat$binwidth     <-readxl::read_excel(data_path, "stock", na = c("", "NA"))$lg_size 
inputs$dat$minimum_size <-readxl::read_excel(data_path, "stock", na = c("", "NA"))$lg_min 
inputs$dat$maximum_size <-readxl::read_excel(data_path, "stock", na = c("", "NA"))$lg_max 
inputs$dat$use_lencomp  <-0 # option SS3
inputs$dat$lbin_vector  <-NULL #seq(inputs$dat$minimum_size, inputs$dat$maximum_size, inputs$dat$binwidth) 
inputs$dat$N_lbins      <-NULL #length(inputs$dat$lbin_vector) 

agemin<-readxl::read_excel(data_path, "stock", na = c("", "NA"))$age_min
agemax<-readxl::read_excel(data_path, "stock", na = c("", "NA"))$age_max
inputs$dat$agebin_vector<-seq(agemin,agemax, 1) 
inputs$dat$N_agebins    <-length(inputs$dat$agebin_vector)
#'*--------------------------------------------------*
#### INFO: catch ----
#'*--------------------------------------------------*
# seasfleet<-as.numeric(readxl::read_excel(data_path, "fleet", na = c("", "NA"))$step_active)
seasfleet<-c(0,7,4,10)
surveytiming0<-round(seasfleet/12,2)#(seasfleet*12/inputs$dat$nseas)/12
surveytiming0[surveytiming0==0]<--1
typefleet<-rep(3,inputs$dat$Nfleets)
typefleet[surveytiming0==-1]<-1

for(i in 1:inputs$dat$Nfleets){
  fleet0<-inputs$dat$fleetnames[i]
  inputs$dat$fleetinfo[fleet0,c("type","surveytiming","area","units","fleetname")]<-c(
    typefleet[i],surveytiming0[i],1,1,fleet0)
}
inputs$dat$fleetinfo[is.na(inputs$dat$fleetinfo)]<-0
inputs$dat$fleetinfo
catchfleet<-length(typefleet[typefleet==1])
fleetnumber<-seq(1,catchfleet,1)

inputs$dat$catch <- rbind(inputs$dat$catch, data.frame(
  year = -999,
  seas = seq_len(inputs$dat$nseas),
  fleet = 1, 
  catch = 0,
  catch_se = 0.01,
  stringsAsFactors = TRUE))
inputs$dat$catch
#'*--------------------------------------------------*
##### Catch data: Seine ----
#'*--------------------------------------------------*
landings_seine <- readxl::read_excel(data_path, "landings_seine", na = c("", "NA"))
landings2024_supuesto<-c(500,3000, 3000,200)

inputs$dat$catch <- rbind(inputs$dat$catch, data.frame(
  year = c(landings_seine$year,2024,2024,2024,2024),
  seas = c(landings_seine$step,1,2,3,4),
  fleet = fleetnumber[1], 
  catch = c(landings_seine[["weight"]],landings2024_supuesto),
  catch_se = 0.1,
  stringsAsFactors = TRUE))
inputs$dat$catch
### Create index ----
for(i in 1:inputs$dat$Nfleets){
  fleet0<-inputs$dat$fleetnames[i]
  inputs$dat$CPUEinfo[fleet0,c("Fleet","Units")]<-c(i,1)
}
inputs$dat$CPUEinfo[is.na(inputs$dat$CPUEinfo)]<-0
inputs$dat$CPUEinfo
#'*--------------------------------------------------*
###  Index Data: ----
#'*--------------------------------------------------*
##### Ecocadiz ----
landings_ecocadiz <- readxl::read_excel(data_path, "dist_si_ecocadiz", na = c("", "NA"))
inputs$dat$CPUE <- rbind(inputs$dat$CPUE, data.frame(
  year = landings_ecocadiz$year,
  seas = landings_ecocadiz$step,
  fleet = inputs$dat$CPUEinfo["ECOCADIZ","Fleet"],
  catch = landings_ecocadiz[["weight"]],
  catch_se = 0.3,
  stringsAsFactors = TRUE))
##### Pelago ----
landings_pelago <- readxl::read_excel(data_path, "dist_si_pelago", na = c("", "NA"))
inputs$dat$CPUE <- rbind(inputs$dat$CPUE, data.frame(
  year = landings_pelago$year,
  seas = landings_pelago$step,
  fleet = inputs$dat$CPUEinfo["PELAGO","Fleet"],
  catch = landings_pelago[["weight"]],
  catch_se = 0.25,
  stringsAsFactors = TRUE))
##### Ecocadiz-Reclutas ----
landings_ECOREC <- readxl::read_excel(data_path, "dist_si_ECOREC", na = c("", "NA"))
inputs$dat$CPUE <- rbind(inputs$dat$CPUE, data.frame(
  year = landings_ECOREC$year,
  seas = landings_ECOREC$step,
  fleet = inputs$dat$CPUEinfo["ECORECLUTAS","Fleet"],
  catch = landings_ECOREC[["weight"]],
  catch_se = 0.2,
  stringsAsFactors = TRUE))

#'*--------------------------------------------------*
### Create age distribution ----
#'*--------------------------------------------------*
#### INFO: age error ----
inputs$dat$N_ageerror_definitions<-1
inputs$dat$ageerror<-inputs$dat$ageerror[c(),c(),drop = FALSE]
inputs$dat$ageerror[1,1:length(inputs$dat$agebin_vector)] <- inputs$dat$agebin_vector+.5
inputs$dat$ageerror[2,1:length(inputs$dat$agebin_vector)] <- 0.001
#### INFO: age composition data  ----
for(i in 1:inputs$dat$Nfleets){
  fleet0<-inputs$dat$fleetnames[i]
  inputs$dat$age_info[fleet0,c("mintailcomp","addtocomp","minsamplesize")]<-c(-1,1e-4,0.001)
}
inputs$dat$age_info[is.na(inputs$dat$age_info)]<-0

if (nrow(inputs$dat$agecomp) == 0) {
  # Seed agecomp with columns based on abin_vector
  cols <- paste0("E", inputs$dat$agebin_vector)
  cols <- structure(as.list(rep(0, length(cols))), names = cols)
  
  inputs$dat$agecomp <- as.data.frame(c(list(
    Yr = 1999,
    Seas = 1,
    Fleet = 1,
    Gender = 0,
    Part = 0,
    Ageerr= 1,
    Lbin_lo=0,
    Lbin_hi=0,
    NSamp = 100), cols))[c(),]
}

#####'*Seine*
# Convert age-lengths into SS-compatible names
aldist_seine <- readxl::read_excel(data_path, "aldist_seine", na = c("", "NA"))
aldist_seine$age <- as.factor(aldist_seine$age)
lvls_a <- parse_levels(levels(aldist_seine$age))
lvls_a_map <- structure(paste0("E", lvls_a$lower_bound), names = lvls_a$names)
levels(aldist_seine$age) <- lvls_a_map[levels(aldist_seine$age)]

#'*--------------------------------------------------*
#'*Age composition*
#'*--------------------------------------------------*
agedist_seine<-aldist_seine%>% 
  group_by(year,step,age) %>% summarise(total=sum(number)) 
# Rotate age groupings, renaming to SS labels
agedist_seine <- reshape2::dcast(agedist_seine,
                                 year + step  ~ age, value.var = "total")

agecomp_Seine<-cbind(data.frame(
  Yr = agedist_seine$year,
  Seas = agedist_seine$step*(12/inputs$dat$nseas),
  Fleet = -inputs$dat$CPUEinfo["SEINE","Fleet"],  
  Gender = 0,
  Part = 0,
  Ageerr= 1,
  Lbin_lo=-1,
  Lbin_hi=-1,
  NSamp = rowSums(agedist_seine[,lvls_a_map]),
  stringsAsFactors = TRUE), agedist_seine[,lvls_a_map])
agecomp_Seine[,lvls_a_map]<-agecomp_Seine[,lvls_a_map]/agecomp_Seine$NSamp #replace number by proportion


#' #'*Age at length*
#' # Rotate age at length groupings, renaming to SS labels
#' aldist_seine <- reshape2::dcast(aldist_seine,
#'                                 year + step + area + length ~ age, value.var = "number")
#' 
#' aldist_seine$length<-as.factor(aldist_seine$length)
#' lvls_l <- parse_levels(levels(aldist_seine$length))
#' lvls_l_map <- structure(lvls_l$lower_bound, names = lvls_l$names)
#' levels(aldist_seine$length) <- lvls_l_map[levels(aldist_seine$length)]
#' 
#' agelencomp_Seine<-cbind(data.frame(
#'   Yr = aldist_seine$year,
#'   Seas = aldist_seine$step*(12/inputs$dat$nseas),
#'   Fleet =  inputs$dat$CPUEinfo["SEINE","Fleet"],  # "seine",  # NB: Use fleetnames for now, will renumber later
#'   Gender = 0,
#'   Part = 0,
#'   Ageerr= 1,
#'   Lbin_lo=aldist_seine$length,
#'   Lbin_hi=aldist_seine$length,
#'   NSamp = rowSums(aldist_seine[,lvls_a_map]),
#'   stringsAsFactors = TRUE), aldist_seine[,lvls_a_map])
#' agelencomp_Seine<-agelencomp_Seine[!agelencomp_Seine$NSamp==0,] # remove row with  size sample equal to 0.
#' agelencomp_Seine[,lvls_a_map]<-agelencomp_Seine[,lvls_a_map]/agelencomp_Seine$NSamp #replace number by proportion
#' 

#####'*Pelago*
# Convert age-lengths into SS-compatible names
aldist_pela <- readxl::read_excel(data_path, "aldist_pelago", na = c("", "NA"))

aldist_pela$age <- as.factor(aldist_pela$age)
lvls_a <- parse_levels(levels(aldist_pela$age))
lvls_a_map <- structure(paste0("E", lvls_a$lower_bound), names = lvls_a$names)
levels(aldist_pela$age) <- lvls_a_map[levels(aldist_pela$age)]

#'*Age composition*
agedist_pela<-aldist_pela%>% 
  group_by(year,step,age) %>% summarise(total=sum(number)) 
# Rotate age groupings, renaming to SS labels
agedist_pela <- reshape2::dcast(agedist_pela,
                                year + step  ~ age, value.var = "total")

agecomp_Pela<-cbind(data.frame(
  Yr = agedist_pela$year,
  Seas = agedist_pela$step,#*(12/inputs$dat$nseas),
  Fleet = -inputs$dat$CPUEinfo["PELAGO","Fleet"],  # "pelago",  # NB: Use fleetnames for now, will renumber later
  Gender = 0,
  Part = 0,
  Ageerr= 1,
  Lbin_lo=-1,
  Lbin_hi=-1,
  NSamp = rowSums(agedist_pela[,lvls_a_map]),
  stringsAsFactors = TRUE), agedist_pela[,lvls_a_map])
agecomp_Pela[,lvls_a_map]<-agecomp_Pela[,lvls_a_map]/agecomp_Pela$NSamp #replace number by proportion



#####'*Ecocadiz-Reclutas*
# Convert age-lengths into SS-compatible names
aldist_ecorec <- readxl::read_excel(data_path, "aldist_ECOREC", na = c("", "NA"))
aldist_ecorec[is.na(aldist_ecorec)] <- 0
aldist_ecorec$age <- as.factor(aldist_ecorec$age)
lvls_a <- parse_levels(levels(aldist_ecorec$age))
lvls_a_map <- structure(paste0("E", lvls_a$lower_bound), names = lvls_a$names)
levels(aldist_ecorec$age) <- lvls_a_map[levels(aldist_ecorec$age)]

#'*Age composition*
agedist_ecorec<-aldist_ecorec%>% 
  group_by(year,step,age) %>% summarise(total=sum(number)) 
# Rotate age groupings, renaming to SS labels
agedist_ecorec <- reshape2::dcast(agedist_ecorec,
                                  year + step  ~ age, value.var = "total")

agecomp_Ecorec<-cbind(data.frame(
  Yr = agedist_ecorec$year,
  Seas = agedist_ecorec$step,#*(12/inputs$dat$nseas),
  Fleet = -inputs$dat$CPUEinfo["ECORECLUTAS","Fleet"],  # "ecocadiz-reclutas",  # NB: Use fleetnames for now, will renumber later
  Gender = 0,
  Part = 0,
  Ageerr= 1,
  Lbin_lo=-1,
  Lbin_hi=-1,
  NSamp = rowSums(agedist_ecorec[,lvls_a_map]),
  stringsAsFactors = TRUE), agedist_ecorec[,lvls_a_map])
agecomp_Ecorec<-agecomp_Ecorec[!agecomp_Ecorec$NSamp==0,] # remove row with  size sample equal to 0.
agecomp_Ecorec[,lvls_a_map]<-agecomp_Ecorec[,lvls_a_map]/agecomp_Ecorec$NSamp #replace number by proportion



#####'*Ecocadiz*
# Convert age-lengths into SS-compatible names
aldist_eco <- readxl::read_excel(data_path, "aldist_ecocadiz", na = c("", "NA"))
aldist_eco[is.na(aldist_eco)] <- 0
aldist_eco$age <- as.factor(aldist_eco$age)
lvls_a <- parse_levels(levels(aldist_eco$age))
lvls_a_map <- structure(paste0("E", lvls_a$lower_bound), names = lvls_a$names)
levels(aldist_eco$age) <- lvls_a_map[levels(aldist_eco$age)]

#'*Age composition*
agedist_eco<-aldist_eco%>% 
  group_by(year,step,age) %>% summarise(total=sum(number)) 
# Rotate age groupings, renaming to SS labels
agedist_eco <- reshape2::dcast(agedist_eco,
                               year + step  ~ age, value.var = "total")

agedist_eco$E0<-0


agecomp_Eco<-cbind(data.frame(
  Yr = agedist_eco$year,
  Seas = agedist_eco$step,#*(12/inputs$dat$nseas),
  Fleet = -inputs$dat$CPUEinfo["ECOCADIZ","Fleet"],  # "ecocadiz",  # NB: Use fleetnames for now, will renumber later
  Gender = 0,
  Part = 0,
  Ageerr= 1,
  Lbin_lo=-1,
  Lbin_hi=-1,
  NSamp = rowSums(agedist_eco[,lvls_a_map]),
  stringsAsFactors = TRUE), agedist_eco[,paste0("E", inputs$dat$agebin_vector)])

agecomp_Eco<-agecomp_Eco[!agecomp_Eco$NSamp==0,] # remove row with  size sample equal to 0.
agecomp_Eco[,lvls_a_map]<-agecomp_Eco[,lvls_a_map]/agecomp_Eco$NSamp #replace number by proportion



inputs$dat$agecomp <- rbind(inputs$dat$agecomp,
                            agecomp_Seine,
                            agecomp_Eco,
                            agecomp_Pela,
                            agecomp_Ecorec) %>% as.data.frame()




#'*--------------------------------------------------*
# CONTROL FILE ----
#'*--------------------------------------------------*
## Empirical Weight
inputs$ctl$EmpiricalWAA<-1
## Growth ----
inputs$ctl$Growth_Age_for_L1<-0
inputs$ctl$Growth_Age_for_L2<-999
## Recruitment season pattern ----
# 0 # 0 means do not read wtatage.ss; 1 means read and usewtatage.ss and also read and use growth parameters
# 1 #_N_Growth_Patterns
# 1 #_N_platoons_Within_GrowthPattern
# 3 # recr_dist_method for parameters
# 1 # not yet implemented; Future usage:Spawner-Recruitment; 1=global; 2=by area
# 4 # number of recruitment settlement assignments 
# 0 # unused option
# # for each settlement assignment:
# #_GPattern	month	area	age
# 1	2	1	0	#_recr_dist_pattern1
# 1	5	1	0	#_recr_dist_pattern2
# 1	8	1	0	#_recr_dist_pattern3
# 1	11	1	0	#_recr_dist_pattern4
inputs$ctl$N_GP <-1 #_N_Growth_Patterns
inputs$ctl$N_platoon <- 1 #_N_platoons_Within_GrowthPattern
inputs$ctl$recr_dist_method <- 3 # recr_dist_method for parameters
inputs$ctl$recr_dist_read <-4 # number of recruitment settlement assignments 
inputs$ctl$recr_dist_pattern <- data.frame(GPattern=c(1,1,1,1),
                                           month=c(2,5,8,11),
                                           area=c(1,1,1,1),
                                           age=c(0,0,0,0))
## Blocks ----
# 1 #_Nblock_Patterns
# 2 #_blocks_per_pattern
# #_begin and end years of blocks
# 1989 2000 2001 2023

#'*N_Block_Designs*
inputs$ctl$N_Block_Designs<-0

#'*blocks_per_pattern*
# block0 <- list()
# block1<-2
# block0[[1]] <- block1
# names(block0)<-"blocks_per_pattern"
# inputs$ctl <- append(inputs$ctl,block0, after = which(names(inputs$ctl)=="N_Block_Designs"))

#'*Block_Design*
# yblock0 <- list()
# yblock1<-data.frame(matrix(c(1989,2000,2001,2023),nrow=1,ncol=4),row.names="boques")
# yblock0[[1]] <- yblock1
# names(yblock0)<-"Block_Design"
# inputs$ctl <- append(inputs$ctl,yblock0, after = which(names(inputs$ctl)=="blocks_per_pattern"))

## Autogen ----
inputs$ctl$time_vary_adjust_method<-1
inputs$ctl$time_vary_auto_generation<-c(0,1,1,1,1)

## Natural mortality ----
inputs$ctl$natM_type <- 3
#'*------------------------------------------------------------------------------*
# #incluir objeto a la lista para el vector de M a la edad
medad0 <- list()
medad1<-data.frame(matrix(c(2.21,1.3,1.3,1.3),nrow=1,ncol=4),row.names="natM1")
colnames(medad1)<-paste("Age_",seq(0,3,1),sep="")
medad0[[1]] <- medad1
names(medad0)<-"natM"
inputs$ctl <- append(inputs$ctl, medad0, after = which(names(inputs$ctl)=="natM_type"))

## Biological params (MG)  ----
#inputs$ctl$MG_parms["NatM", c("LO","HI","INIT","PHASE")]       <- c(0.05,1.13,0.3,-3)
inputs$ctl$MG_parms["L_at_Amin", c("LO","HI","INIT","PHASE")]  <- c(0,10, 6,3)
inputs$ctl$MG_parms["L_at_Amax", c("LO","HI","INIT","PHASE")]  <- c(5,22,19.96,-3)
inputs$ctl$MG_parms["VonBert_k", c("LO","HI","INIT","PHASE")]  <- c(0.1,2,0.46,3)
inputs$ctl$MG_parms["CV_young", c("LO","HI","INIT","PHASE")]   <- c(0.05,0.25,0.1,-3)
inputs$ctl$MG_parms["CV_old", c("LO","HI","INIT","PHASE")]     <- c(0.05,0.25,0.1,-3)
inputs$ctl$MG_parms["Wtlen_1", c("LO","HI","INIT","PHASE")]    <- c(-3,3,0.00000313,-3) # kg
inputs$ctl$MG_parms["Wtlen_2", c("LO","HI","INIT","PHASE")]    <- c(-3,3,3.278,-3) # kg
inputs$ctl$MG_parms["Mat50%", c("LO","HI","INIT","PHASE")]     <- c(-3,15,22,-3)
inputs$ctl$MG_parms["Mat_slope", c("LO","HI","INIT","PHASE")]  <- c(-3,3,-0.45,-3)
inputs$ctl$MG_parms["Eggs_alpha", c("LO","HI","INIT","PHASE")] <- c(-3,3,1,-3)
inputs$ctl$MG_parms["Eggs_beta", c("LO","HI","INIT","PHASE")]  <- c(-3,3,0,-3)

inputs$ctl$MG_parms["RecrDist_month_1", c("LO","HI","INIT","PHASE","dev_link","dev_minyr","dev_maxyr","dev_PH")]  <- c(0,2,0,4,3,1989,2024,3)
inputs$ctl$MG_parms["RecrDist_month_2", c("LO","HI","INIT","PHASE","dev_link","dev_minyr","dev_maxyr","dev_PH")]  <- c(0,2,0,4,3,1989,2024,3)
inputs$ctl$MG_parms["RecrDist_month_3", c("LO","HI","INIT","PHASE","dev_link","dev_minyr","dev_maxyr","dev_PH")]  <- c(0,2,0.25,4,3,1989,2024,3)
inputs$ctl$MG_parms["RecrDist_month_4", c("LO","HI","INIT","PHASE","dev_link","dev_minyr","dev_maxyr","dev_PH")]  <- c(0,2,0.75,4,3,1989,2024,3)
# 0   2   0.25 1 99 0 2 0 0 0 0 0 0 0 #_RecrDist_month_1 
# 0   2   0.25 1 99 0 2 0 0 0 0 0 0 0 #_RecrDist_month_2 


inputs$ctl$MG_parms["CohortGrowDev", c("LO","HI","INIT","PHASE")] <- c(1,1,1,-3)
inputs$ctl$MG_parms["FracFemale", c("LO","HI","INIT","PHASE")]  <- c(0.0000001,0.9999999,0.5,-3)


inputs$ctl$MG_parms[is.na(inputs$ctl$MG_parms)]<-0

inputs$ctl$MG_parms

## Stock-recruitment (SR) ----
inputs$ctl$SR_function <- 4
inputs$ctl$SR_parms["SR_LN(R0)", c("LO","HI","INIT","PHASE")] <- c(5,20,10,1)
inputs$ctl$SR_parms["SR_SCAA_null", c("LO","HI","INIT","PHASE")] <- c(0.2,1,0.9,-4)
inputs$ctl$SR_parms["SR_sigmaR", c("LO","HI","INIT","PHASE")] <- c(0,2,0.6,-4)
inputs$ctl$SR_parms["SR_regime", c("LO","HI","INIT","PHASE")] <- c(-5,5,0,-4)
inputs$ctl$SR_parms["SR_autocorr", c("LO","HI","INIT","PHASE")] <- c(0,0,0,-4)
inputs$ctl$SR_parms[is.na(inputs$ctl$SR_parms)]<-0

inputs$ctl$SR_parms

## Recruitment deviation (recDev)  ----
inputs$ctl$MainRdevYrFirst<-inputs$dat$styr
inputs$ctl$MainRdevYrLast<-inputs$dat$endyr  
inputs$ctl$recdev_phase<-1
inputs$ctl$recdev_adv<-0

## Fishing Mortality (F) ----
inputs$ctl$F_ballpark_year<- -inputs$dat$endyr 
inputs$ctl$init_F<-NULL

## Catchability (Q) ----
### Catchability options ----
for(i in 2:inputs$dat$Nfleets){
  fleet<-inputs$dat$fleetnames[i]
  inputs$ctl$Q_options[fleet,c("fleet","link")] <- c(i,1)
}
inputs$ctl$Q_options[is.na(inputs$ctl$Q_options)]<-0

inputs$ctl$Q_options

### Catchability Parameters: ----
# for(i in 2:inputs$dat$Nfleets){
# fleet<-inputs$dat$fleetnames[i]
inputs$ctl$Q_parms[paste0("LnQ_base_",inputs$dat$fleetnames[2]),c("LO","HI","INIT","PHASE")] <- c(-30,15,0.1,3)#"ECOCADIZ"
inputs$ctl$Q_parms[paste0("LnQ_base_",inputs$dat$fleetnames[3]),c("LO","HI","INIT","PHASE")] <- c(-30,15,0.1,2)#"PELAGO"
inputs$ctl$Q_parms[paste0("LnQ_base_",inputs$dat$fleetnames[4]),c("LO","HI","INIT","PHASE")] <- c(-30,15,0.1,2)#"ECORECLUTAS"
#}
inputs$ctl$Q_parms[is.na(inputs$ctl$Q_parms)]<-0


## Selectivity (Sel) ----

### Selectivity Options: ----
####'*Size selex* 
# for(i in 1:inputs$dat$Nfleets){
#   fleet<-inputs$dat$fleetnames[i]
#inputs$ctl$size_selex_types[inputs$dat$fleetnames[1],"Pattern"] <- 1#"SEINE"
#inputs$ctl$size_selex_types[inputs$dat$fleetnames[2],"Pattern"] <- 1#"ECOCADIZ"
#inputs$ctl$size_selex_types[inputs$dat$fleetnames[3],"Pattern"] <- 1#"PELAGO"
#inputs$ctl$size_selex_types[inputs$dat$fleetnames[4],"Pattern"] <- 0#"ECORECLUTAS"
#}
#inputs$ctl$size_selex_types[is.na(inputs$ctl$size_selex_types)]<-0
#inputs$ctl$size_selex_types

####'*Age selex*
# for(i in 1:inputs$dat$Nfleets){
#   fleet<-inputs$dat$fleetnames[i]
inputs$ctl$age_selex_types[inputs$dat$fleetnames[1],"Pattern"] <- 12#"SEINE"
inputs$ctl$age_selex_types[inputs$dat$fleetnames[2],"Pattern"] <- 12#"ECOCADIZ"
inputs$ctl$age_selex_types[inputs$dat$fleetnames[3],"Pattern"] <- 10#"PELAGO"
inputs$ctl$age_selex_types[inputs$dat$fleetnames[4],"Pattern"] <- 12#"ECORECLUTAS"
#}
inputs$ctl$age_selex_types[is.na(inputs$ctl$age_selex_types)]<-0
inputs$ctl$age_selex_types

### Selectivity Parameters: ----
#### Size selex ----
#for(i in 1:inputs$dat$Nfleets){
#'*"seine"* 
#'  fleet1<-inputs$dat$fleetnames[1] 
#'  inputs$ctl$size_selex_parms[paste0("SizeSel_P_1_",fleet1),
#'                              c("LO","HI","INIT","PHASE","Block", "Block_Fxn")] <- c(-1,10,8,2,1,2)
#'  inputs$ctl$size_selex_parms[paste0("SizeSel_P_2_",fleet1),
#'                              c("LO","HI","INIT","PHASE")] <- c(-1,20,10,2)
#' #' #'*"ecocadiz"*
#'  fleet2<-inputs$dat$fleetnames[2] 
#'  inputs$ctl$size_selex_parms[paste0("SizeSel_P_1_",fleet2),
#'                              c("LO","HI","INIT","PHASE")] <- c(-1,15,10,3)
#'  inputs$ctl$size_selex_parms[paste0("SizeSel_P_2_",fleet2),
#'                              c("LO","HI","INIT","PHASE")] <- c(-1,20,12,3)
#'  #'*"pelago"*
#'  fleet3<-inputs$dat$fleetnames[3] 
#'  inputs$ctl$size_selex_parms[paste0("SizeSel_P_1_",fleet3),
#'                              c("LO","HI","INIT","PHASE")] <- c(-3,15,10,3)
#'  inputs$ctl$size_selex_parms[paste0("SizeSel_P_2_",fleet3),
#'                              c("LO","HI","INIT","PHASE")] <- c(-3,20,12,3)
#' #' #'*"ECOREC"*
#'  fleet4<-inputs$dat$fleetnames[4] 
#'  inputs$ctl$size_selex_parms[paste0("SizeSel_P_1_",fleet4),
#'                              c("LO","HI","INIT","PHASE")] <- "#" #c(-1,20,8,2)
#'  inputs$ctl$size_selex_parms[paste0("SizeSel_P_2_",fleet4),
#'                              c("LO","HI","INIT","PHASE")] <- "#"# c(-1,20,10,2)
#' #' #}
#'  inputs$ctl$size_selex_parms[is.na(inputs$ctl$size_selex_parms)]<-0

#_SizeSelex
# #_LO	HI	INIT	PRIOR	PR_SD	PR_type	PHASE	env-var	use_dev	dev_mnyr	dev_mxyr	dev_PH	Block	Blk_Fxn  #  parm_name
# -1	10	8 	0	0	0	2	0	0	0	0	0	1	2	#_SizeSel_P_1_SEINE      
# -1	20	10	0	0	0	2	0	0	0	0	0	0	0	#_SizeSel_P_2_SEINE      
# -1	15	10	0	0	0	3	0	0	0	0	0	0	0	#_SizeSel_P_1_ECOCADIZ   
# -1	20	12	0	0	0	3	0	0	0	0	0	0	0	#_SizeSel_P_2_ECOCADIZ   
# -3	15	10	0	0	0	3	0	0	0	0	0	0	0	#_SizeSel_P_1_PELAGO     
# -3	20	12	0	0	0	3	0	0	0	0	0	0	0	#_SizeSel_P_2_PELAGO     
# # 	# 	# 	0	0	0	#	0	0	0	0	0	0	0	#_SizeSel_P_1_ECORECLUTAS
# # 	# 	# 	0	0	0	#	0	0	0	0	0	0	0	#_SizeSel_P_2_ECORECLUTAS
# #_AgeSelex
# #_No age_selex_parm
# # timevary selex parameters 
# #_LO	HI	INIT	PRIOR	PR_SD	PR_type	PHASE
#  -1	  15	8 	  0	    0	    0	      3		#_SizeSel_P_1_SEINE_1 
#  -1	  15	10 	  0	    0	    0	      3		#_SizeSel_P_1_SEINE_2 

# #incluir objeto a la lista para timevary selex parameters

# DoVar_adjust0 <- list()
#  DoVar_adjust1<-1
#  DoVar_adjust0[[1]] <- DoVar_adjust1
#  names(DoVar_adjust0)<-"DoVar_adjust"
#  inputs$ctl <- append(inputs$ctl,DoVar_adjust0, after = which(names(inputs$ctl)=="TG_custom"))
#  
#  
# timevaySel0 <- list()
# timevaySel1<-t(data.frame(SizeSel_P_1_SEINE_1=c(-1,15,8,0,0,0,3),
#                           SizeSel_P_1_SEINE_2=c(-1,15,10,0,0,0,3)))
# colnames(timevaySel1)<-c("LO",	"HI",	"INIT","PRIOR","PR_SD","PR_type","PHASE")
# timevaySel0[[1]] <- timevaySel1
# names(timevaySel0)<-"timevary_selex_parameters"
# 
# after_index <- which(names(inputs$ctl) == "size_selex_parms")[1]
# inputs$ctl <- append(inputs$ctl, timevaySel0, after=after_index)

#### Age selex ----
# for(i in 1:inputs$dat$Nfleets){
#   fleet<-inputs$dat$fleetnames[i]
fleet1<-inputs$dat$fleetnames[1] #"seine"
 inputs$ctl$age_selex_parms[paste0("AgeSel_P_1_",fleet1),
                            c("LO","HI","INIT","PHASE")] <- c(-2,5.5,0,3)

 inputs$ctl$age_selex_parms[paste0("AgeSel_P_2_",fleet1),
                            c("LO","HI","INIT","PHASE")] <- c(-1,5.5,1,3)

 fleet2<-inputs$dat$fleetnames[2]
 inputs$ctl$age_selex_parms[paste0("AgeSel_P_1_",fleet2),
                            c("LO","HI","INIT","PHASE")] <- c(-2,5.5,0,3)
 inputs$ctl$age_selex_parms[paste0("AgeSel_P_2_",fleet2),
                            c("LO","HI","INIT","PHASE")] <- c(-1,5.5,1,3)

 fleet3<-inputs$dat$fleetnames[3] #"pelago"
 inputs$ctl$age_selex_parms[paste0("AgeSel_P_1_",fleet3),
                            c("LO","HI","INIT","PHASE")] <- "#" #c(-2,5.5,0,3)
 inputs$ctl$age_selex_parms[paste0("AgeSel_P_2_",fleet3),
                            c("LO","HI","INIT","PHASE")] <- "#" #c(-1,5.5,1,3)

 fleet4<-inputs$dat$fleetnames[4] #""ECOREC"
 inputs$ctl$age_selex_parms[paste0("AgeSel_P_1_",fleet4),
                            c("LO","HI","INIT","PHASE")] <- c(-2,5.5,0,3)
 inputs$ctl$age_selex_parms[paste0("AgeSel_P_2_",fleet4),
                            c("LO","HI","INIT","PHASE")] <- c(-1,5.5,1,3)


 inputs$ctl$age_selex_parms[is.na(inputs$ctl$age_selex_parms)]<-0


#inputs$ctl$age_selex_parms<-NULL

## Lambdas ----
#which(names(inputs$ctl)=="TG_custom")
# DoVar_adjust0 <- list()
# DoVar_adjust1<-1
# DoVar_adjust0[[1]] <- DoVar_adjust1
# names(DoVar_adjust0)<-"DoVar_adjust"
# inputs$ctl <- append(inputs$ctl,DoVar_adjust0, after = which(names(inputs$ctl)=="TG_custom"))

# #incluir objeto a la lista 

nmfleets0 <- list()
nmfleets1<-data.frame(Data_type=c(4,4,4,4,6,6,6,6),
                      fleet=c(1,2,3,4,1,2,3,4),
                      Value=c(0.0583234, 
                              0.0638579,
                              0.0598173,
                              0.0553717,
                              0.0127546,
                              0.0359210,
                              0.0055257,
                              0.0557137),
                      row.names=c("Variance_adjustment_list1",
                                  "Variance_adjustment_list2",
                                  "Variance_adjustment_list3",
                                  "Variance_adjustment_list4", 
                                  "Variance_adjustment_list5", 
                                  "Variance_adjustment_list6",
                                  "Variance_adjustment_list7", 
                                  "Variance_adjustment_list8"))
nmfleets0[[1]] <- nmfleets1
names(nmfleets0)<-"Variance_adjustment_list"

after_index <- which(names(inputs$ctl) == "DoVar_adjust")[1]
#inputs$ctl <- append(inputs$ctl, nmfleets0, after = after_index)
#inputs$ctl <- append(inputs$ctl,nmfleets0, after = which(names(inputs$ctl)=="DoVar_adjust"))

#inputs$ctl$maxlambdaphase<- 1

#inputs$ctl$N_lambdas <- nrow(inputs$ctl$lambdas)
#if (nrow(inputs$ctl$lambdas) == 0) inputs$ctl$lambdas <- NULL
#inputs$ctl$more_stddev_reporting<-0



# STARTER FILE ----
inputs$start$F_report_units<-5
inputs$start$F_age_range<-c(2,3)

# FORECAST FILE ----
inputs$fore

# RUN AND OUTPUTS ----
## Write back to mod_path  ----

# WATAGE FILE ----

#inputs$wtatage

watFleetSeane0<-data.frame(Yr=0,
           Seas=0,
           Sex=0,
           Bio_Pattern=0,
           BirthSeas=0,
           Fleet=0)



r4ss::SS_write(inputs, dir = mod_path, overwrite = TRUE)

